In [1]:
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = X[:, 0] ^ X[:, 1]
y

X = PolynomialFeatures(interaction_only=True).fit_transform(X).astype(int)
X




clf = Perceptron(fit_intercept=False, max_iter=10, tol=None,
                 shuffle=False).fit(X, y)

In [7]:
y

array([0, 1, 1, 0])

In [5]:
X

array([[1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [4]:
X[:, 0] 

array([1, 1, 1, 1])

In [6]:
X[:, 1]

array([0, 0, 1, 1])

In [3]:
clf.predict(X)

array([0, 1, 1, 0])

In [2]:
clf.score(X, y)

1.0